export const BANGLADESH_LOCATIONS = {
  divisions: [
    { id: '1', name: 'Dhaka' },
    { id: '2', name: 'Chattogram' },
    { id: '3', name: 'Rajshahi' },
    { id: '4', name: 'Khulna' },
    { id: '5', name: 'Barishal' },
    { id: '6', name: 'Sylhet' },
    { id: '7', name: 'Rangpur' },
    { id: '8', name: 'Mymensingh' },
  ],
  districts: [
    // Dhaka
    { id: '1', division_id: '1', name: 'Dhaka' },
    { id: '2', division_id: '1', name: 'Gazipur' },
    { id: '3', division_id: '1', name: 'Narsingdi' },
    { id: '4', division_id: '1', name: 'Manikganj' },
    { id: '5', division_id: '1', name: 'Munshiganj' },
    { id: '6', division_id: '1', name: 'Narayanganj' },
    { id: '7', division_id: '1', name: 'Tangail' },
    { id: '8', division_id: '1', name: 'Faridpur' },
    { id: '9', division_id: '1', name: 'Gopalganj' },
    { id: '10', division_id: '1', name: 'Kishoreganj' },
    { id: '11', division_id: '1', name: 'Madaripur' },
    { id: '12', division_id: '1', name: 'Rajbari' },
    { id: '13', division_id: '1', name: 'Shariatpur' },
    // Chattogram
    { id: '14', division_id: '2', name: 'Chattogram' },
    { id: '15', division_id: '2', name: 'Cox’s Bazar' },
    { id: '16', division_id: '2', name: 'Comilla' },
    { id: '17', division_id: '2', name: 'Chandpur' },
    { id: '18', division_id: '2', name: 'Noakhali' },
    { id: '19', division_id: '2', name: 'Feni' },
    { id: '20', division_id: '2', name: 'Lakshmipur' },
    { id: '21', division_id: '2', name: 'Brahmanbaria' },
    { id: '22', division_id: '2', name: 'Khagrachhari' },
    { id: '23', division_id: '2', name: 'Rangamati' },
    { id: '24', division_id: '2', name: 'Bandarban' },
    // Rajshahi
    { id: '25', division_id: '3', name: 'Rajshahi' },
    { id: '26', division_id: '3', name: 'Bogura' },
    { id: '27', division_id: '3', name: 'Pabna' },
    { id: '28', division_id: '3', name: 'Sirajganj' },
    { id: '29', division_id: '3', name: 'Naogaon' },
    { id: '30', division_id: '3', name: 'Natore' },
    { id: '31', division_id: '3', name: 'Joypurhat' },
    { id: '32', division_id: '3', name: 'Chapainawabganj' },
    // Khulna
    { id: '33', division_id: '4', name: 'Khulna' },
    { id: '34', division_id: '4', name: 'Jessore' },
    { id: '35', division_id: '4', name: 'Satkhira' },
    { id: '36', division_id: '4', name: 'Bagerhat' },
    { id: '37', division_id: '4', name: 'Narail' },
    { id: '38', division_id: '4', name: 'Kushtia' },
    { id: '39', division_id: '4', name: 'Jhenaidah' },
    { id: '40', division_id: '4', name: 'Magura' },
    { id: '41', division_id: '4', name: 'Chuadanga' },
    { id: '42', division_id: '4', name: 'Meherpur' },
    // Barishal
    { id: '43', division_id: '5', name: 'Barishal' },
    { id: '44', division_id: '5', name: 'Bhola' },
    { id: '45', division_id: '5', name: 'Patuakhali' },
    { id: '46', division_id: '5', name: 'Barguna' },
    { id: '47', division_id: '5', name: 'Jhalokati' },
    { id: '48', division_id: '5', name: 'Pirojpur' },
    // Sylhet
    { id: '49', division_id: '6', name: 'Sylhet' },
    { id: '50', division_id: '6', name: 'Moulvibazar' },
    { id: '51', division_id: '6', name: 'Habiganj' },
    { id: '52', division_id: '6', name: 'Sunamganj' },
    // Rangpur
    { id: '53', division_id: '7', name: 'Rangpur' },
    { id: '54', division_id: '7', name: 'Dinajpur' },
    { id: '55', division_id: '7', name: 'Thakurgaon' },
    { id: '56', division_id: '7', name: 'Panchagarh' },
    { id: '57', division_id: '7', name: 'Nilphamari' },
    { id: '58', division_id: '7', name: 'Lalmonirhat' },
    { id: '59', division_id: '7', name: 'Kurigram' },
    { id: '60', division_id: '7', name: 'Gaibandha' },
    // Mymensingh
    { id: '61', division_id: '8', name: 'Mymensingh' },
    { id: '62', division_id: '8', name: 'Jamalpur' },
    { id: '63', division_id: '8', name: 'Sherpur' },
    { id: '64', division_id: '8', name: 'Netrokona' },
  ],
  upazilas: [
    // Dhaka District Upazilas
    { id: '1', district_id: '1', name: 'Dhamrai' },
    { id: '2', district_id: '1', name: 'Dohar' },
    { id: '3', district_id: '1', name: 'Keraniganj' },
    { id: '4', district_id: '1', name: 'Nawabganj' },
    { id: '5', district_id: '1', name: 'Savar' },
    // Gazipur District Upazilas
    { id: '6', district_id: '2', name: 'Gazipur Sadar' },
    { id: '7', district_id: '2', name: 'Kaliakair' },
    { id: '8', district_id: '2', name: 'Kaliganj' },
    { id: '9', district_id: '2', name: 'Kapasia' },
    { id: '10', district_id: '2', name: 'Sreepur' },
    // Narayanganj District Upazilas
    { id: '11', district_id: '6', name: 'Araihazar' },
    { id: '12', district_id: '6', name: 'Bandar' },
    { id: '13', district_id: '6', name: 'Narayanganj Sadar' },
    { id: '14', district_id: '6', name: 'Rupganj' },
    { id: '15', district_id: '6', name: 'Sonargaon' },
    // Chattogram District Upazilas
    { id: '16', district_id: '14', name: 'Anwara' },
    { id: '17', district_id: '14', name: 'Banshkhali' },
    { id: '18', district_id: '14', name: 'Boalkhali' },
    { id: '19', district_id: '14', name: 'Chandanaish' },
    { id: '20', district_id: '14', name: 'Fatikchhari' },
    { id: '21', district_id: '14', name: 'Hathazari' },
    { id: '22', district_id: '14', name: 'Lohagara' },
    { id: '23', district_id: '14', name: 'Mirsharai' },
    { id: '24', district_id: '14', name: 'Patiya' },
    { id: '25', district_id: '14', name: 'Rangunia' },
    { id: '26', district_id: '14', name: 'Raozan' },
    { id: '27', district_id: '14', name: 'Sandwip' },
    { id: '28', district_id: '14', name: 'Satkania' },
    { id: '29', district_id: '14', name: 'Sitakunda' },
    // Narail District Upazilas (ID: 37)
    { id: '30', district_id: '37', name: 'Narail Sadar' },
    { id: '31', district_id: '37', name: 'Lohagara' },
    { id: '32', district_id: '37', name: 'Kalia' },
    // Khulna District Upazilas (ID: 33)
    { id: '33', district_id: '33', name: 'Batiaghata' },
    { id: '34', district_id: '33', name: 'Dacope' },
    { id: '35', district_id: '33', name: 'Dumuria' },
    { id: '36', district_id: '33', name: 'Dighalia' },
    { id: '37', district_id: '33', name: 'Koyra' },
    { id: '38', district_id: '33', name: 'Paikgacha' },
    { id: '39', district_id: '33', name: 'Phultala' },
    { id: '40', district_id: '33', name: 'Rupsha' },
    { id: '41', district_id: '33', name: 'Terokhada' },
    // Jessore District Upazilas (ID: 34)
    { id: '42', district_id: '34', name: 'Abhaynagar' },
    { id: '43', district_id: '34', name: 'Bagherpara' },
    { id: '44', district_id: '34', name: 'Chaugachha' },
    { id: '45', district_id: '34', name: 'Jhikargachha' },
    { id: '46', district_id: '34', name: 'Keshabpur' },
    { id: '47', district_id: '34', name: 'Manirampur' },
    { id: '48', district_id: '34', name: 'Sharsha' },
    // Manikganj District Upazilas (ID: 4)
    { id: '49', district_id: '4', name: 'Manikganj Sadar' },
    { id: '50', district_id: '4', name: 'Singair' },
    { id: '51', district_id: '4', name: 'Saturia' },
    { id: '52', district_id: '4', name: 'Harirampur' },
    { id: '53', district_id: '4', name: 'Ghior' },
    { id: '54', district_id: '4', name: 'Daulatpur' },
    { id: '55', district_id: '4', name: 'Shibalaya' },
  ]
};
